/*
 * @lc app=leetcode id=26 lang=c
 *
 * [26] Remove Duplicates from Sorted Array
 *
 * autogenerated using scripts/convert.py
 */
int removeDuplicates(int* nums, int numsSize) {
    int n = 0, c, i;
    
    for (i = 0; i < numsSize; ++i) {
        if (i == 0 || nums[i] != nums[i - 1])
            nums[n++] = nums[i];
    }
    
    return n;
}
