/*
 * @lc app=leetcode id=263 lang=c
 *
 * [263] Ugly Number
 *
 * autogenerated using scripts/convert.py
 */
bool isUgly(int num) {
    if (num <= 0)
        return 0;
    
    while (! (num % 2))
        num /= 2;
    while (! (num % 3))
        num /= 3;
    while (! (num % 5))
        num /= 5;
    
    return num == 1;
}
