/*
 * @lc app=leetcode id=28 lang=c
 *
 * [28] Implement strStr()
 *
 * autogenerated using scripts/convert.py
 */
#include <string.h>

int strStr(char* haystack, char* needle) {
    int len = strlen(needle);
    char *p = haystack;
    
    if (! len)
        return 0;
    
    while (*p && strncmp(p, needle, len))
        ++p;
    
    return (*p ? (int)(p - haystack) : -1);
}
