/*
 * @lc app=leetcode id=35 lang=c
 *
 * [35] Search Insert Position
 *
 * autogenerated using scripts/convert.py
 */
int searchInsert(int* nums, int numsSize, int target) {
    int i;
    
    for (i = 0; i < numsSize; ++i) {
        if (nums[i] >= target)
            return i;
    }
    return numsSize;
}
