/*
 * @lc app=leetcode id=392 lang=c
 *
 * [392] Is Subsequence
 *
 * autogenerated using scripts/convert.py
 */
bool isSubsequence(char* s, char* t) {
    while (*s && *t) {
        if (*t++ == *s)
            ++s;
    }
    
    return ! *s;
}
