/*
 * @lc app=leetcode id=434 lang=c
 *
 * [434] Number of Segments in a String
 *
 * autogenerated using scripts/convert.py
 */
int countSegments(char* s) {
    int ret = 0;
    
    while (*s) {
        if (*s == ' ') {
            s++;
            continue;
        }
        ++ret;
        
        while (*s && *s != ' ')
            ++s;
    }
    
    return ret;
}
