/*
 * @lc app=leetcode id=476 lang=c
 *
 * [476] Number Complement
 *
 * autogenerated using scripts/convert.py
 */
int findComplement(int num) {
    int k = 0;
    for (k; num >> k; ++k)
        ;
    return ((~num) & ((1 << k) - 1));
}