/*
 * @lc app=leetcode id=650 lang=c
 *
 * [650] 2 Keys Keyboard
 *
 * autogenerated using scripts/convert.py
 */
int minSteps(int n) {
    int i;
    
    if (n == 1)
        return 0;
    
    for (i = 2; i * i <= n; ++i) {
        if (n % i == 0)
            return i + minSteps(n / i);
    }
    
    return n;
}
