/*
 * @lc app=leetcode id=9 lang=c
 *
 * [9] Palindrome Number
 *
 * autogenerated using scripts/convert.py
 */
bool isPalindrome(int x) {
    int reverse = 0, copy = x;
    
    if (x < 0)
        return 0;
    
    while (copy) {
        reverse *= 10;
        reverse += copy % 10;
        copy /= 10;
    }
    
    return (x == reverse);
}
