/*
 * @lc app=leetcode id=201 lang=java
 *
 * [201] Bitwise AND of Numbers Range
 *
 * autogenerated using scripts/convert.py
 */
public class Solution {
    public int rangeBitwiseAnd(int m, int n) {
        int mask = Integer.MAX_VALUE;
        
        while ((m & mask) != (n & mask))
            mask <<= 1;
        
        return m & mask;
    }
}
