/*
 * @lc app=leetcode id=319 lang=java
 *
 * [319] Bulb Switcher
 *
 * autogenerated using scripts/convert.py
 */
public class Solution {
    public int bulbSwitch(int n) {
        return (int)Math.floor(Math.sqrt(n));
    }
}
