/*
 * @lc app=leetcode id=470 lang=java
 *
 * [470] Implement Rand10() Using Rand7()
 *
 * autogenerated using scripts/convert.py
 */
/**
 * The rand7() API is already defined in the parent class SolBase.
 * public int rand7();
 * @return a random integer in the range 1 to 7
 */
class Solution extends SolBase {
    public int rand10() {
        while (true) {
            int r = 7 * (rand7() - 1) + (rand7() - 1);
            
            if (r < 40) {
                return r % 10 + 1;
            }
        }
    }
}