/*
 * @lc app=leetcode id=520 lang=java
 *
 * [520] Detect Capital
 *
 * autogenerated using scripts/convert.py
 */
class Solution {
    public boolean detectCapitalUse(String word) {
        return word.matches("^([A-Z]+)|([A-Z][a-z]+)|([a-z]+)$");
    }
}
