/*
 * @lc app=leetcode id=64 lang=java
 *
 * [64] Minimum Path Sum
 *
 * autogenerated using scripts/convert.py
 */
public class Solution {
    public int minPathSum(int[][] grid) {
        int m = grid.length, n = grid[0].length, i, j;
        int[][] dp = new int[m][n];
        
        dp[0][0] = grid[0][0];
        for (i = 1; i < m; ++i)
            dp[i][0] = grid[i][0] + dp[i - 1][0];
        for (j = 1; j < n; ++j)
            dp[0][j] = grid[0][j] + dp[0][j - 1];
        
        for (i = 1; i < m; ++i) {
            for (j = 1; j < n; ++j) {
                dp[i][j] = grid[i][j] + Math.min(dp[i - 1][j], dp[i][j - 1]);
            }
        }
        
        return dp[m - 1][n - 1];
    }
}
