/*
 * @lc app=leetcode id=693 lang=java
 *
 * [693] Binary Number with Alternating Bits
 *
 * autogenerated using scripts/convert.py
 */
class Solution {
    public boolean hasAlternatingBits(int n) {
        String s = Integer.toBinaryString(n);
        return s.indexOf("00") == -1 && s.indexOf("11") == -1;
    }
}