#
# @lc app=leetcode id=1 lang=python3
#
# [1] Two Sum
#
# autogenerated using scripts/convert.py
#
class Solution(object):
    def twoSum(self, nums, target):
        """
        :type nums: List[int]
        :type target: int
        :rtype: List[int]
        """
        for a in range(len(nums)):
            for b in range(a + 1, len(nums)):
                if nums[a] + nums[b] == target:
                    return [a, b]
                    