#
# @lc app=leetcode id=344 lang=python3
#
# [344] Reverse String
#
# autogenerated using scripts/convert.py
#
class Solution(object):
    def reverseString(self, s):
        """
        :type s: str
        :rtype: str
        """
        return s[::-1]