#
# @lc app=leetcode id=557 lang=python3
#
# [557] Reverse Words in a String III
#
# autogenerated using scripts/convert.py
#
class Solution(object):
    def reverseWords(self, s):
        """
        :type s: str
        :rtype: str
        """
        return ' '.join([x[::-1] for x in s.split(' ')])
