#
# @lc app=leetcode id=769 lang=python3
#
# [769] Max Chunks To Make Sorted
#
# autogenerated using scripts/convert.py
#
class Solution:
    def maxChunksToSorted(self, arr):
        """
        :type arr: List[int]
        :rtype: int
        """
        m = 0
        ret = 0
        for i, v in enumerate(arr):
            m = max(v, m)
            if i == m:
                ret += 1
        return ret