--
-- @lc app=leetcode id=178 lang=mysql
--
-- [178] Rank Scores
--
-- autogenerated using scripts/convert.py
--
# Write your MySQL query statement below
SELECT Score,
(SELECT COUNT(DISTINCT Score) FROM Scores WHERE Score >= s.Score) Rank
FROM Scores s ORDER BY Score DESC;
